---
title: "ecommerce"
date: '2022-05-21'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, comment = NA, message = F, warning = F, fig.align = "center")
options(pillar.sigfig = 7)
options(scipen = 999)
```
```{r Libraries}

library(tidyverse)
library(ggcorrplot)
library(ggmosaic)
library(ggpubr)
library(interactions)
library(ggpubr) # for publication ready plots
library(broom) # for tidy function
library(forestmangr)
library(pROC)


```

```{r}
Data_Ecommerce<-read_csv("ecommerce.csv")%>% as_tibble()
glimpse(Data_Ecommerce)
summary(Data_Ecommerce)

Data_Ecommerce<- Data_Ecommerce %>%
  mutate(discount=factor(discount),
         conversion=factor(conversion),
         source=factor(source),
         country=factor(country)) %>% as_tibble()

glimpse(Data_Ecommerce)
summary(Data_Ecommerce)

```

```{r constructing logistic regression model}
m1<-glm(conversion~discount, data = Data_Ecommerce, family = binomial())
m1
summary(m1)

```

```{r Discountyes Odd ratio}
odds_ratio<-exp(1.10090)
odds_ratio
```
```{r fo 95% confidence interval}
exp(coef(m1))
exp(confint(m1))

tidy(m1) %>% # tidy function from broom package
  mutate(exp_beta_llci = exp(confint(m1))[, 1], # lower ci
         exp_beta = exp(estimate), # odds ratio, midpoint
         exp_beta_ulci = exp(confint(m1))[, 2]) %>% # upper 
  select(term, estimate, exp_beta_llci, exp_beta, exp_beta_ulci)



```

```{r construct a Double decker mosaic plot}

table(Data_Ecommerce$conversion, Data_Ecommerce$source)
ggplot(data = Data_Ecommerce) + # start a ggplot
  geom_mosaic(aes( # use a mosaic geom
    x = product(discount),  # put 'promo' on x-axis
    fill = conversion), # use `pass` as fill color
    offset = 0.02, # set the space in-between
    divider = ddecker()) + # double decker plot
  facet_grid(~source,# forms a matrix of panels by 'channel'
             scales = "free") + # let both facet height and width vary
  theme_pubr() + # use this theme
  theme(axis.text.y = element_blank(), # clustomize the theme
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(angle = 90)) +
  labs(x = "", y = "") # don't use axis labels

```

```{r construct the logistic regression model }
m2 <- glm(conversion~discount+source, data = Data_Ecommerce, family = binomial)
m2
summary(m2)


exp(coef(m2))
# confidence intervals for odds ratios
exp(confint(m2))
(1 - exp(confint(m2))[2, 2]) * 100
(1 - exp(confint(m2))[2, 1]) * 100
(1 + exp(confint(m2))[2, 2]) * 100
(1 + exp(confint(m2))[2, 2])
(1 + exp(confint(m2))[2, 1])
```

```{r contruct logistic regression model}
m3<- glm(conversion~discount+
           source+
           discount:source,
         data = Data_Ecommerce, family = binomial)
m3
summary(m3)
exp(coef(m3))
tidy(m3) %>% # tidy function from broom package
  mutate(exp_beta_llci = exp(confint(m3))[, 1], # lower ci
         exp_beta = exp(estimate), # odds ratio, midpoint
         exp_beta_ulci = exp(confint(m3))[, 2]) %>% # upper 
  select(term, estimate, exp_beta_llci, exp_beta, exp_beta_ulci)
  
  tidy(m3) %>% # tidy function from broom package
  mutate(exp_beta_llci = exp(confint(m3))[, 1], # lower ci
         exp_beta = exp(estimate), # odds ratio, midpoint
         exp_beta_ulci = exp(confint(m3))[, 2]) %>% # upper 
  select(term, estimate, exp_beta_llci, exp_beta, exp_beta_ulci) %>% 
  ggplot(aes(x = term, 
             y = exp_beta,
             ymin = exp_beta_llci,
             ymax = exp_beta_ulci)) +
  geom_point(size = 4) + 
  geom_errorbar(width = 0.25) +
  # add a horizontal line where odds ratio == 1.0 (no effect):
  geom_hline(yintercept = 1, linetype = "dashed", 
                    size = 1, color = "dodgerblue") + 
  labs(title = "95% CI: Customer purchaced odds by terms",
       x = NULL,
       y = "Likehood by Factor (odds ratio, main effect)") + 
  coord_flip() + # rotates the plot
  theme_pubr()


```

```{r  Build logistic regression model which predicts conversion of all available variables}
m4<- glm(conversion~discount+
           source+
           total_pages_visited+
           visit_duration+
           country+
           discount:source,
         data = Data_Ecommerce, family = binomial)
m4
summary(m4)
```

```{r Correlation between total pages visited and visit duration}
cor(Data_Ecommerce[,c("total_pages_visited",
            "visit_duration")])

cor(Data_Ecommerce[,c("total_pages_visited",
            "visit_duration")]) %>% round(2)

r.mat<-cor(Data_Ecommerce[,c("total_pages_visited",
                   "visit_duration")])

p.mat<-cor_pmat(Data_Ecommerce[,c("total_pages_visited",
                        "visit_duration")])
p.mat
ggcorrplot(r.mat,
           type = "lower", # display only lower triangle
           p.mat = p.mat, # combine with significance
           lab = T)
cor(Data_Ecommerce$total_pages_visited, Data_Ecommerce$visit_duration)

```

```{r Build logistic regression model from the m4 by removing the visit duration}
m5<- glm(conversion~discount+
           source+
            total_pages_visited+
           country+
           discount:source,
         data = Data_Ecommerce, family = binomial)
m5
summary(m5)
```

```{r Plot that will visualises the odds ratio}
tidy(m5) %>% # tidy function from broom package
  mutate(exp_beta_llci = exp(confint(m5))[, 1], # lower ci
         exp_beta = exp(estimate), # odds ratio, midpoint
         exp_beta_ulci = exp(confint(m5))[, 2]) %>% # upper
  select(term, estimate, exp_beta_llci, exp_beta, exp_beta_ulci) %>%
  ggplot(aes(x = term,
             y = exp_beta,
             ymin = exp_beta_llci,
             ymax = exp_beta_ulci)) +
  geom_point(size = 4) +
  geom_errorbar(width = 0.25) +
  # add a horizontal line where odds ratio == 1.0 (no effect):
  geom_hline(yintercept = 1, linetype = "dashed",
             size = 1, color = "dodgerblue") +
  labs(title = "95% CI: Customer purchased odds by factor",
       x = NULL,
       y = "Likehood by Factor (odds ratio, main effect)") +
  coord_flip() + # rotates the plot
  theme_pubr()
```

```{r}

Data_Ecommerce$base_prob <-predict( # store the predictions onto a new variable
  m5, # use the full model
  type = "response") # calculate logit probabilities

head(Data_Ecommerce)
summary(Data_Ecommerce$base_prob)

```

```{r}
Data_Ecommerce$pred_conversion<-1 * (Data_Ecommerce$base_prob >= 0.5)
summary(Data_Ecommerce$pred_conversion)
table(Data_Ecommerce$conversion, Data_Ecommerce$pred_conversion)

```

```{r HIT rate}

hit.rate<-(20190+908)*100/25046
hit.rate
```

```{r}

# store the output of the roc fuction onto an object
rocobj <- roc(Data_Ecommerce$conversion,
              Data_Ecommerce$pred_conversion) # predictions
# area under the curve
rocobj$auc
# plot the ROC curve
ggroc(rocobj,
      color = "dodgerblue",
      size = 1,
      legacy.axes = T) + # the specificity axis (x axis) plotted as increasing “1 - specificity”
  geom_segment(x = 0, y = 0, xend = 1, yend = 1, linetype = 2, alpha  =  0.01) + # plot the diagonal line
  theme_pubr() +
  labs(title = sprintf("ROC Curve (AUC = %.5f)", rocobj$auc), # plot the auc as title
       x = "1 - Specificity (or fpr)",
       y = "Sensitivity (or tpr)")

```

```{r}
new_prob<-Data_Ecommerce
new_prob$total_pages_visited <- new_prob$total_pages_visited + 1
new_prob$new_prob <- predict(m5,
                             new_prob,
                             type = "response")
mean(new_prob$base_prob)
mean(new_prob$new_prob)

```

```{r}
liftmetric<-(mean(new_prob$new_prob)-mean(new_prob$base_prob))/mean(new_prob$base_prob)
liftmetric
```